import streamlit as st
import requests

st.set_page_config(
    page_title="AI Drug Guardrail Dashboard",
    page_icon="🧬",
    layout="wide"
)

st.title("🧬 Post-LLM Generative AI Drug Guardrail System")
st.markdown("""
This system evaluates chemical compounds generated by LLMs to flag **synthetic intractability** or **Blood-Brain Barrier (BBB)** failure before lab synthesis.
""")

st.write("---")

col1, col2 = st.columns([1, 2])

with col1:
    st.subheader("Chemical Input Pipeline")
    
    # Input field where researchers type or paste their AI-generated drug candidate strings
    smiles_input = st.text_input(
        "Enter Chemical SMILES String:", 
        value="CC(=O)NC1=CC=C(C=C1)O"
    )
    
    submit_button = st.button("Analyze Compound Profile", type="primary")

with col2:
    st.subheader("Automated Evaluation Output Logs")
    
    if submit_button:
        with st.spinner("Executing background API model inference..."):
            try:
                # Direct HTTP POST request to your stateless FastAPI backend container
                backend_url = "http://localhost:8000/predict"
                payload = {"smiles": smiles_input}
                
                response = requests.post(backend_url, json=payload)
                
                if response.status_code == 200:
                    data = response.json()
                    
                    # Display metrics instantly in clean visual cards
                    metric_col1, metric_col2 = st.columns(2)
                    with metric_col1:
                        st.metric("BBB Penetration State", str(data["blood_brain_barrier_penetration"]))
                    with metric_col2:
                        st.metric("Synthetic Complexity Score", f"{data['synthetic_complexity_score']} / 10.0")
                    
                    st.write("---")
                    
                    rec = data["action_recommended"]
                    if "Approve" in rec:
                        st.success(f"**Recommendation Outcome:** {rec}")
                    else:
                        st.error(f"**Recommendation Outcome:** {rec}")
                        
                    # Show the raw structured JSON packet returned from the API
                    with st.expander("Examine Production API JSON Response Packet"):
                        st.json(data)
                        
                else:
                    st.error(f"Backend Server returned an error code: {response.status_code}")
                    st.write(response.text)
                    
            except requests.exceptions.ConnectionError:
                st.error("Could not reach the FastAPI backend server layer. Please make sure your server is running on port 8000.")
    else:
        st.info("Awaiting Input Payload. Enter a valid chemical structural sequence and trigger evaluation to display analytics.")